services:
  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.14.4
    container_name: wazuh-indexer
    hostname: wazuh.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer:/usr/share/wazuh-indexer/config
    networks:
          - wazuh-network

  wazuh.manager:
    image: wazuh/wazuh-manager:4.14.4
    container_name: wazuh-manager
    hostname: wazuh.manager
    restart: always
    ports:
      - "1514:1514"       # Recepción de eventos de agentes
      - "1515:1515"       # Registro de agentes
      - "514:514/udp"     # Syslog
      - "55000:55000"     # API REST de Wazuh
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - FILEBEAT_SSL_VERIFICATION_MODE=full
    volumes:
      - wazuh-manager-data:/var/ossec/data
      - wazuh-manager-logs:/var/ossec/logs
      - ./config/wazuh_manager:/wazuh-config-mount/etc
    networks:
      - wazuh-network
    depends_on:
      - wazuh.indexer

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.14.4
    container_name: wazuh-dashboard
    hostname: wazuh.dashboard
    restart: always
    ports:
      - "443:5601"
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=${API_PASSWORD}
    networks:
      - wazuh-network
    volumes:
      - wazuh-dashboard-data:/usr/share/wazuh-dashboard/data
      - ./config/wazuh_dashboard:/wazuh-config-mount/etc/wazuh-dashboard
    depends_on:
      - wazuh.indexer
      - wazuh.manager

wazuh.agent:
    image: ubuntu:22.04
    container_name: wazuh-agent
    hostname: wazuh-agent
    restart: always
    environment:
      - WAZUH_MANAGER=wazuh.manager
      - WAZUH_AGENT_NAME=agente-laboratorio
    command: >
      bash -c "apt-get update -y &&
               apt-get install -y curl lsb-release &&
               curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --dearmor -o /usr/share/keyrings/wazuh.gpg &&
               echo 'deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main' > /etc/apt/sources.list.d/wazuh.list &&
               apt-get update -y &&
               WAZUH_MANAGER=wazuh.manager WAZUH_AGENT_NAME=agente-laboratorio apt-get install -y wazuh-agent=4.14.4-1 &&
               /var/ossec/bin/wazuh-control start &&
               tail -f /var/ossec/logs/ossec.log"
    depends_on:
      - wazuh.manager
    networks:
      - wazuh-network

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:
  wazuh-manager-logs:
  wazuh-dashboard-data:

networks:
  wazuh-network:
    driver: bridge